services:
  - type: web
    name: gull-autos
    env: python
    buildCommand: pip install -r requirements-base.txt
    startCommand: gunicorn gull_autos.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
    autoDeploy: true
