services:
  - type: web
    name: gull-autos
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 8000
    autoDeploy: true
