services:
  - type: web
    name: gull-autos
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 8000
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: gull_autos.settings
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      # Add these in Render dashboard for security
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        value: us-east-1
    autoDeploy: true
