# Generated by Django 5.0.4 on 2024-12-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_view_count_product_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='compatibility',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
