# Generated by Django 5.0.4 on 2024-12-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blogpost_options_remove_blogpost_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(default='No Subject', max_length=200),
        ),
    ]
