# Generated by Django 5.0 on 2024-12-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
